---
- name: Install Apache and starts the service
  hosts: webserver
  tasks:
  - name: Install required packages
    dnf:
      name: "{{ ansible_local.custom.general.package }}"
      state: latest

  - name: Start the service
    service:
      name: "{{ ansible_local.custom.general.service }}"
      state: "{{ ansible_local.custom.general.state }}"
      enabled: "{{ ansible_local.custom.general.enabled }}"

