---
- name: Test intranet web server
  hosts: localhost
  become: false
  tasks:
  - name: Connect to intranet web server
    ansible.builtin.uri:
      url: http://servera.lab.example.com
      return_content: yes
      status_code: 200
