---
- name: Enable intranet services
  hosts: serverb.lab.example.com
  become: true
  tasks:
  - name: Latest version of packages installed
    ansible.builtin.dnf:
      name: 
      - httpd
      - firewalld
      - mariadb-server
      - php
      - php-mysqlnd
      state: latest

  - name: Firewalld enabled and running
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: true
  
  - name: Firewall permits access to httpd service
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
 
  - name: httpd enabled and running
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
  
  
  - name: mariadb enabled and running
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: true
  
  - name: Test html page is installed
    ansible.builtin.copy:
      src: /home/student/playbook-review/index.php
      dest: /var/www/html/index.html
      mode: 0644
  

- name: Test intranet web server
  hosts: workstation
  become: false
  tasks:
  - name: Connect to intranet web server
    ansible.builtin.uri:
      url: http://serverb.lab.example.com
      return_content: yes
      status_code: 200
